import { readFile, readdir, stat } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const catalog = JSON.parse(await readFile(new URL("data/catalog.json", root), "utf8"));
const styles = await readFile(new URL("assets/styles.css", root), "utf8");
const app = await readFile(new URL("assets/app.js", root), "utf8");
const admin = await readFile(new URL("assets/admin.js", root), "utf8");
const storeHtml = await readFile(new URL("index.html", root), "utf8");
const adminHtml = await readFile(new URL("admin.html", root), "utf8");
const authFunction = await readFile(new URL("supabase/functions/request-auth-code/index.ts", root), "utf8");
const keepAliveWorkflow = await readFile(new URL(".github/workflows/manter-supabase-ativo.yml", root), "utf8");
const productFiles = await readdir(new URL("products/", root));
const expected = new Set(catalog.map(item => item.image_url.split("/").pop()));
const missing = [...expected].filter(name => !productFiles.includes(name));
const empty = [];
for (const name of productFiles) if ((await stat(new URL(`products/${name}`, root))).size === 0) empty.push(name);

if (catalog.length !== 88) throw new Error(`Esperados 88 produtos; encontrados ${catalog.length}.`);
if (expected.size !== 83) throw new Error(`Esperadas 83 imagens únicas; encontradas ${expected.size}.`);
if (missing.length) throw new Error(`Imagens ausentes: ${missing.join(", ")}`);
if (empty.length) throw new Error(`Imagens vazias: ${empty.join(", ")}`);

const options = catalog.flatMap(item => item.option_groups.flatMap(group => group.options));
if (options.length !== 304) throw new Error(`Esperadas 304 opções; encontradas ${options.length}.`);
if (!styles.includes("height:calc(100dvh - 16px)")) throw new Error("O modal móvel não acompanha a altura visível da tela.");
if (!styles.includes("overflow-y:auto;overscroll-behavior:contain")) throw new Error("A rolagem do modal móvel não está ativa.");
if (!styles.includes("object-fit:contain")) throw new Error("As imagens dos produtos podem ser recortadas.");
if (!styles.includes(".quantity-row{position:sticky;bottom:0")) throw new Error("A barra de adicionar não está presa à base do modal.");
if (!app.includes("requestAnimationFrame") || !app.includes("scrollTop=0")) throw new Error("O modal não volta ao início ao abrir outro produto.");
if (!authFunction.includes("auth.admin.generateLink") || !authFunction.includes("password: generatedPassword")) throw new Error("O cadastro não gera o OTP oficial com uma senha técnica válida.");
if (!authFunction.includes('from "npm:nodemailer') || !authFunction.includes('rpc("override_auth_otp"')) throw new Error("O envio personalizado de seis dígitos não está ativo.");
if (authFunction.includes("auth.signInWithOtp")) throw new Error("O envio ainda pode usar o template padrão com link.");
if (!authFunction.includes('verificationType = "email"') || !authFunction.includes('type: "magiclink"')) throw new Error("O cadastro incompleto não recebe um novo OTP.");
if (!app.includes("state.otpType=data?.verificationType||null") || !app.includes('state.otpType||(state.authMode==="recovery"?"recovery":"email")')) throw new Error("A validação não usa o tipo de OTP retornado pelo servidor.");
if (!app.includes("token.length<6||token.length>8") || !admin.includes("/^\\d{6,8}$/")) throw new Error("As telas não aceitam o OTP numérico oficial.");
if (!storeHtml.includes('pattern="[0-9]{6,8}" maxlength="8"') || !adminHtml.includes('maxlength="8" pattern="[0-9]{6,8}"')) throw new Error("Os campos de OTP não aceitam códigos de 6 a 8 dígitos.");
if (!keepAliveWorkflow.includes('cron: "17 9 * * *"') || !keepAliveWorkflow.includes("workflow_dispatch:")) throw new Error("O robô diário do Supabase não está agendado corretamente.");
if (!keepAliveWorkflow.includes("/rest/v1/store_settings") || !keepAliveWorkflow.includes("--retry 3")) throw new Error("O robô diário não valida o banco com repetição segura.");
if (/service[_-]?role/i.test(keepAliveWorkflow)) throw new Error("O robô diário não pode usar a chave administrativa.");
console.log(`OK: ${catalog.length} produtos, ${expected.size} imagens, ${options.length} opções, modal móvel rolável e robô diário do Supabase.`);
